export enum QueryKey {
  POSTS = 'POSTS',
  POST = 'POST',
  COMMENTS = 'COMMENTS',
  USERS = 'USERS',
  USER_PROFILE = 'USER_PROFILE',
  FRIENDS_ME = 'FRIENDS_ME',
  USER_LIKED_POSTS = 'USER_LIKED_POSTS',
  ADMIN_LOGS = 'ADMIN_LOGS',
}
