/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as MeRouteImport } from './routes/me'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserPostsPostIdRouteImport } from './routes/user-posts.$postId'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as ChatUserIdRouteImport } from './routes/chat.$userId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPostsPostIdRoute = UserPostsPostIdRouteImport.update({
  id: '/user-posts/$postId',
  path: '/user-posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatUserIdRoute = ChatUserIdRouteImport.update({
  id: '/chat/$userId',
  path: '/chat/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/posts': typeof PostsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/chat/$userId': typeof ChatUserIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/user-posts/$postId': typeof UserPostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/posts': typeof PostsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/chat/$userId': typeof ChatUserIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/user-posts/$postId': typeof UserPostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/posts': typeof PostsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/chat/$userId': typeof ChatUserIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/user-posts/$postId': typeof UserPostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/me'
    | '/posts'
    | '/sign-in'
    | '/sign-up'
    | '/users'
    | '/verify-email'
    | '/chat/$userId'
    | '/profile/$userId'
    | '/user-posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/me'
    | '/posts'
    | '/sign-in'
    | '/sign-up'
    | '/users'
    | '/verify-email'
    | '/chat/$userId'
    | '/profile/$userId'
    | '/user-posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/me'
    | '/posts'
    | '/sign-in'
    | '/sign-up'
    | '/users'
    | '/verify-email'
    | '/chat/$userId'
    | '/profile/$userId'
    | '/user-posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeRoute: typeof MeRoute
  PostsRoute: typeof PostsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UsersRoute: typeof UsersRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ChatUserIdRoute: typeof ChatUserIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  UserPostsPostIdRoute: typeof UserPostsPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-posts/$postId': {
      id: '/user-posts/$postId'
      path: '/user-posts/$postId'
      fullPath: '/user-posts/$postId'
      preLoaderRoute: typeof UserPostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$userId': {
      id: '/chat/$userId'
      path: '/chat/$userId'
      fullPath: '/chat/$userId'
      preLoaderRoute: typeof ChatUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeRoute: MeRoute,
  PostsRoute: PostsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UsersRoute: UsersRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ChatUserIdRoute: ChatUserIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  UserPostsPostIdRoute: UserPostsPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
